### ISSUE TITLE
Why does "fs" uses ".." for the current directory when "require" uses "."?

### ISSUE THREAD

**Issue by helmasaur** [Helmasaur/ac-keijiban#20]
Line [12](https://github.com/Helmasaur/ac-keijiban/blob/dev/index.js#L12) vs. lines [18](https://github.com/Helmasaur/ac-keijiban/blob/dev/index.js#L18), [19](https://github.com/Helmasaur/ac-keijiban/blob/dev/index.js#L19) and [20](https://github.com/Helmasaur/ac-keijiban/blob/dev/index.js#L20).

**Comment by arobase-che** [comment]
[require](https://www.freecodecamp.org/news/requiring-modules-in-node-js-everything-you-need-to-know-e7fbd119be8/).
